- repository: autowarefoundation/autoware.universe
  files:
    - source: .github/workflows/build-and-test.yaml
    - source: .github/workflows/build-and-test-differential.yaml
    - source: .github/workflows/build-and-test-differential-self-hosted.yaml
    - source: .github/workflows/build-and-test-self-hosted.yaml
    - source: .github/workflows/check-build-depends.yaml
    - source: .github/workflows/clang-tidy-pr-comments.yaml
    - source: codecov.yaml
